name: RHDA Workflow

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  rhda_job:
    runs-on: ubuntu-latest
    name: Testing RHDA action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
          skopeo --version

      - name: Use Personal Access Token with Octokit
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: process.env.MY_PAT });
          const github = require('@actions/github');
  
          const prNumber = 14; // Example pull request number
  
          // Working call for both org and personal repositories
          const labelsResponse = await octokit.paginate("GET /repos/{owner}/{repo}/labels", {
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
          });

          console.log(labelsResponse);
  
          // The problematic call
          const issueLabelsResponse = await octokit.paginate("GET /repos/{owner}/{repo}/issues/{issue_number}/labels", {
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            issue_number: prNumber,
          });
  
          console.log(issueLabelsResponse);
        
      - name: RHDA analysis
        uses: RHEcosystemAppEng/rhda-github-action@chore/remove-user-auth
        with:
          use_python_virtual_environment: "true"
          github_token: ${{ secrets.MY_PAT }}

        env:
          GHT: ${{ vars.MY_PAT }}
        
